server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

    health:
      group:
        custom:
          show-details: always

spring:
  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/giseladonoso
    username: giseladonoso
    password:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
